hmcts/pip-cron-trigger

- Dockerfile
- README.md
- src/main/java/uk/gov/hmcts/reform/pip/cron/trigger/config/CronTimerProperties.java
- src/main/java/uk/gov/hmcts/reform/pip/cron/trigger/runner/ScheduleRunner.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/pip/cron/trigger/config/CronTimerPropertiesTest.java
- src/test/java/uk/gov/hmcts/reform/pip/cron/trigger/runner/ScheduleRunnerTest.java
https://tools.hmcts.net/jira/browse/PUB-1591
Updated to use environment variables instead of args due to testing in the build pipeline
```
[ ] Yes
[x] No
```
> PUB-1591 - Updated dockerfile

- README.md
- build.gradle
- charts/pip-cron-trigger/Chart.yaml
- charts/pip-cron-trigger/values.yaml
- src/main/java/uk/gov/hmcts/reform/pip/cron/trigger/model/ScheduleTypes.java
- src/main/java/uk/gov/hmcts/reform/pip/cron/trigger/triggers/MiDataReportingTrigger.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/pip/cron/trigger/triggers/MiDataReportingTriggerTest.java
- src/test/resources/application-test.yaml
https://tools.hmcts.net/jira/browse/PUB-1551
Add trigger to generate MI data reporting by calling out to publication services
```
[ ] Yes
[x] No
```
> PUB-1551 Add trigger for MI report generation

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/pip/cron/trigger/config/owasp/suppressions.xml
CVE-31690, CVE-31692 and CVE-42252 fixes and suppression
```
[ ] Yes
[x] No
```
> CVE-31690, CVE-31692 and CVE-42252 fixes and suppression

- build.gradle
- config/owasp/suppressions.xml
N/A
Update suppressions / dependencies
```
[ ] Yes
[x] No
```
> Updated dependencies

- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PUB-1811
Added defaults for terraform variables
```
[ ] Yes
[x] No
```
> PUB-1811 - Removed uneeded variables

- build.gradle
- charts/pip-cron-trigger/Chart.yaml
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PUB-1910
Update dependencies + suppressions
```
[ ] Yes
[x] No
```
> PUB-1910 - Updated dependencies + suppressions

- build.gradle
- charts/pip-cron-trigger/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-1970
Updated dependencies + suppressions + chart
```
[ ] Yes
[x] No
```
> PUB-1970 - Updated dependencies + suppressions + chart

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-1996
Updated dependencies
```
[ ] Yes
[x] No
```
> PUB-1996 - Update dependencies

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-1996
Updated dependencies
```
[ ] Yes
[x] No
```
> PUB-1996 - Updated dependencies

- .github/workflows/ci.yml
- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-1687
- Upgraded spring to V3
- Updated checkstyle version
- Updated PMD version
- Excluded commons logging
- Updated github action to use Java 17
```
[ ] Yes
[x] No
```
> PUB-1687 - Upgraded spring

- build.gradle
- config/owasp/suppressions.xml
N/A
Fixed vulnerability
```
[ ] Yes
[x] No
```
> Updated vulnerability

- build.gradle
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PUB-2119
Updated dependencies + suppressions
Spring Dependency Management to 1.1.2
Sonarqube to 4.3.0.3225
Active Directory starter to 5.3.0
jUnit to 5.10.0
Gradle version to 8.2.1
```
[ ] Yes
[x] No
```
> PUB-2119 - Updated dependencies + suppressions

- build.gradle
- config/owasp/suppressions.xml
N/A
Fixed Spring CVE
```
[ ] Yes
[x] No
```
> Fixed spring CVE

- .github/dependabot.yml
- .github/renovate.json
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-2144
Updated to use renovate
```
[ ] Yes
[x] No
```
> PUB-2124 - Updated renovate

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-2192
Added suppressions
```
[ ] Yes
[x] No
```
> PUB-2192 - Updated suppressions

- config/owasp/suppressions.xml
N/A
Add suppression - already on latest version of parent dependency
```
[ ] Yes
[x] No
```
> Add suppression

- .github/workflows/ci.yml
- build.gradle
- config/owasp/suppressions.xml
N/A
Owasp dependency check
```
[ ] Yes
[x] No
```
> Updated owasp version

- .github/workflows/terraform_format.yml
- infrastructure/state.tf
https://tools.hmcts.net/jira/browse/PUB-2182
Add terraform_format.yml
```
[ ] Yes
[x] No
```
> PUB-2182 add terraform_format.yml

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-2133
Updated to Spring Boot 3.2
```
[ ] Yes
[x] No
```
> PUB-2133 - Updated spring boot

- Jenkinsfile_nightly
- README.md
- build.gradle
- charts/pip-cron-trigger/Chart.yaml
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/PUB-1619
Added fortify
```
[ ] Yes
[x] No
```
> PUB-1619 - Updated fortify

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PUB-1619
Fixed nightly build
```
[ ] Yes
[x] No
```
> PUB-1619 - Fixed nightly

- .github/workflows/ci.yml
- Dockerfile
- README.md
- build.gradle
- src/test/java/uk/gov/hmcts/reform/pip/cron/trigger/runner/ScheduleRunnerTest.java
https://tools.hmcts.net/jira/browse/PUB-2461
Upgrading to Java 21
```
[ ] Yes
[x] No
```
> PUB-2461: Upgrading to Java 21

- Jenkinsfile_nightly
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-2490
Updated nightly build time
```
[ ] Yes
[x] No
```
> PUB-2490 - Updated nightly time

- build.gradle
- charts/pip-cron-trigger/Chart.yaml
https://tools.hmcts.net/jira/browse/PUB-2827
Updated to use new version of helm chart
```
[ ] Yes
[x] No
```
> PUB-2827 - Updated helm chart
